class_name WorldSim
extends RefCounted
## The live world (LAYER 2 in the spec): islands, placed buildings, the shared
## stockpiles, the 6 global currencies, population, and the game clock. Owns the
## deterministic per-tick resolution and idle/offline catch-up.
##
## It is a plain RefCounted object (not an autoload) so the whole sim is reachable
## headless in `--script` test runs. The `Game` autoload owns one instance and ticks
## it; UI connects to these signals. Matches the spec's "one WorldState object".
##
## PER-TICK RESOLUTION ORDER (fixed, golden-asserted):
##   1. connectivity → 2. production → 3. consumption/needs →
##   4. population dynamics → 5. economy payout.

signal economy_ticked(delta_seconds: float)
signal building_placed(building_id: String, cell: Vector2i)
signal building_removed(cell: Vector2i)
signal population_changed(tier_id: String, residents: int, total: int)
signal needs_unmet(tier_id: String, missing_good: String)
signal tier_unlocked(tier_id: String)
signal research_completed(perk_id: String)
signal notify(text: String, level: String)
signal expedition_launched(island_index: int, camp_id: int)
signal expedition_resolved(island_index: int, camp_id: int, won: bool)
signal world_changed()  ## islands discovered / settled / handed over (macro map dirty)
signal reputation_earned(total: int)  ## a Palace completed → +1 permanent Reputation

const CREATIVITY_PER_POP_PER_MIN := 0.5  ## CHOSEN DEFAULT (per-resident Creativity rate)
const MAX_STEP := 0.5           ## seconds per integration sub-tick (fixed quantum)
const MAX_CATCHUP_ITERS := 600  ## bound on offline catch-up iterations (no startup freeze)
const GROW_INTERVAL := 6.0      ## seconds of full basics before +1 resident
const EMIGRATE_INTERVAL := 10.0 ## seconds of unmet basics before −1 resident
const FAVOR_PER_PARAGON_PER_MIN := 0.2  ## CHOSEN DEFAULT (Paragon Favor output)
const MILITIA_PER_POP_PER_MIN := 0.2    ## CHOSEN DEFAULT (a satisfied house musters Militia)
const ARMY_CAP := 100                   ## units per expedition (raised by Bannerman/General)
const ISLAND_LIMIT_BASE := 3            ## settled islands (raised by Better Relations / Minion)
const DISCOVERY_TRAVEL_BASE := 120.0    ## CHOSEN DEFAULT base discovery travel time (s)
const DISCOVERY_SEC_PER_POINT := 600.0  ## spec: +10 min per Cartography point spent
const DISCOVERY_CAP := 2.5 * 24.0 * 3600.0  ## spec: discovery total caps at 2.5 days
const PALACE_PARAGON_REQ := 30      ## CHOSEN DEFAULT (scaled from spec's 500 Paragons)
const PALACE_MAX_STAGE := 5         ## Foundation (0) + 5 Favor-fuelled stages
## Favor to upgrade the Palace from stage i to i+1 (scaled from spec 1875/3750/7500/15000).
const PALACE_STAGE_FAVOR := [200.0, 400.0, 800.0, 1600.0, 3200.0]

var islands: Array[Island] = []
var active_index: int = 0
var currencies: Dictionary = {"coin": 0.0, "cartography": 0.0, "favor": 0.0, "reputation": 0.0}
var unlocked_tiers: Array = ["pioneers"]
var creativity: float = 0.0     ## research currency, generated by population
var researched: Array = []      ## perk ids (a repeatable perk appears once per rank)
var elapsed: float = 0.0        ## total simulated game seconds
var unlocked_regions: Array = ["temperate"]  ## climate regions reachable (research-gated)
var discoveries: Array = []     ## in-flight island-discovery voyages
var trade_routes: Array = []    ## continuous inter-island good transfers (ships)
var expeditions: Array = []     ## in-flight battles (resolve over wall-clock time)
var active_custodians: Array = []  ## prestige run-modifiers chosen at New Game+
var _exp_seq: int = 0           ## monotonic expedition counter → deterministic seeds
var _disc_seq: int = 0          ## monotonic discovery counter → deterministic island seeds
var _mods: Dictionary = {}      ## derived economy modifiers from `researched`
var _tick_accum: float = 0.0    ## sub-tick remainder carried across advance() calls
var _last_emit: float = 0.0     ## throttle the economy_ticked UI signal

# ── lifecycle ────────────────────────────────────────────────────────────────

func active_island() -> Island:
	if islands.is_empty():
		return null
	return islands[active_index]

## Fresh run: one generated temperate island with a coastal Kontor and a small
## starting stockpile so the player can build immediately. `custodians` are the
## prestige run-modifiers chosen at New Game+; `start_reputation` carries the
## permanent Reputation total over from the meta layer.
func new_game(seed_value := 1337, custodians: Array = [], start_reputation := 0) -> void:
	islands.clear()
	active_custodians = custodians.duplicate()
	currencies = {"coin": 200.0, "cartography": 0.0, "favor": 0.0,
		"reputation": float(start_reputation)}
	unlocked_tiers = ["pioneers"]
	unlocked_regions = ["temperate"]
	creativity = 0.0
	researched = []
	expeditions = []
	discoveries = []
	trade_routes = []
	_exp_seq = 0
	_disc_seq = 0
	_recompute_mods()
	_apply_custodian_starts()
	elapsed = 0.0
	_tick_accum = 0.0
	# The home island carries two forts — a weak camp (first conquest) and the
	# Warchief Bula fort, whose defeat grants the first Cartography point (gating
	# expansion). Bula (size-12 boss) is the temperate-game military objective.
	var isl := MapGen.generate(32, 32, seed_value, "temperate", 2, "bula")
	isl.island_name = "Verdant Isle"
	isl.settled = true
	isl.stockpile = {"wood": 80.0, "plank": 30.0}
	islands.append(isl)
	active_index = 0
	_place_starting_kontor(isl)
	_recompute_connectivity(isl)

## Restart in place on THIS instance — keeps HUD/IslandView signal connections valid
## (they bound to this object in their _ready). See Game.restart().
func reset(seed_value := 1337, custodians: Array = [], start_reputation := 0) -> void:
	new_game(seed_value, custodians, start_reputation)

func _place_starting_kontor(isl: Island) -> void:
	var def := Database.building("kontor")
	var center := Vector2i(isl.width / 2, isl.height / 2)
	for radius in range(0, max(isl.width, isl.height)):
		for dy in range(-radius, radius + 1):
			for dx in range(-radius, radius + 1):
				if abs(dx) != radius and abs(dy) != radius:
					continue
				var origin := center + Vector2i(dx, dy)
				if isl.can_place(def, origin).ok:
					isl.place(def, origin)
					return

# ── the tick ──────────────────────────────────────────────────────────────────

## Advance the simulation by `dt` real seconds. The remainder below one MAX_STEP is
## CARRIED across calls (not re-partitioned), so the tick stream — and therefore the
## resulting state — depends only on total elapsed time, not on how dt was chopped.
## This is what makes advance(a)+advance(b) == advance(a+b) actually hold.
func advance(dt: float) -> void:
	if dt <= 0.0:
		return
	_tick_accum += dt
	while _tick_accum >= MAX_STEP:
		_tick(MAX_STEP)
		_tick_accum -= MAX_STEP
		elapsed += MAX_STEP
	_last_emit += dt
	if _last_emit >= 0.2:
		_last_emit = 0.0
		economy_ticked.emit(dt)

## Offline catch-up: simulate `seconds` in a BOUNDED number of coarse steps so loading
## after a long absence never freezes the first frame. Coarser than the real-time
## quantum (minor fidelity trade-off for the one-shot replay; the per-tick logic is
## frame-rate independent so growth/emigration still resolve correctly at large steps).
func catch_up(seconds: float) -> void:
	if seconds <= 0.0:
		return
	var step: float = max(MAX_STEP, seconds / float(MAX_CATCHUP_ITERS))
	var remaining := seconds
	while remaining > 0.0001:
		var s: float = min(remaining, step)
		_tick(s)
		elapsed += s
		remaining -= s

func _tick(dt: float) -> void:
	for isl in islands:
		_recompute_connectivity(isl)
		_phase_production(isl, dt)
		_phase_population(isl, dt)
	# Creativity accrues from total population (decoupled from luxury satisfaction, so
	# research never stalls during an economy transition).
	var cmult := float(_mods.get("creativity_mult", 1.0)) if not _mods.is_empty() else 1.0
	creativity += total_population() * (CREATIVITY_PER_POP_PER_MIN / 60.0) * dt * cmult
	_advance_expeditions(dt)
	_advance_discoveries(dt)
	_advance_trade(dt)

# Phase 1: who is within range of a storage building (no roads — pure proximity).
func _recompute_connectivity(isl: Island) -> void:
	var storages: Array = []
	for pb in isl.buildings:
		var def := Database.building(pb.building_id)
		if def != null and def.is_storage:
			storages.append({"center": _center(def, pb.origin), "range": def.storage_range})
	for pb in isl.buildings:
		var def := Database.building(pb.building_id)
		if def == null:
			continue
		if def.is_storage:
			pb.connected = true
			continue
		var c := _center(def, pb.origin)
		pb.connected = false
		for s in storages:
			var d: Vector2i = c - s.center
			if max(abs(d.x), abs(d.y)) <= int(s.range):
				pb.connected = true
				break

func _center(def: BuildingDef, origin: Vector2i) -> Vector2i:
	return origin + Vector2i(def.size.x / 2, def.size.y / 2)

# Phase 2: production. Each whole iteration consumes inputs from island storage and
# adds the output. Starved buildings hold at most one iteration of banked progress.
func _phase_production(isl: Island, dt: float) -> void:
	for pb in isl.buildings:
		var def := Database.building(pb.building_id)
		if def == null or def.recipe == null:
			continue
		pb.active = false
		if not pb.connected:
			continue
		var r := def.recipe
		pb.progress += dt
		if pb.progress < r.iteration_time:
			continue
		var iters := int(pb.progress / r.iteration_time)
		for good_id in r.inputs:
			var amt: float = r.inputs[good_id]
			if amt > 0.0:
				iters = min(iters, int(isl.qty(good_id) / amt))
		iters = max(iters, 0)
		if iters > 0:
			for good_id in r.inputs:
				isl.take(good_id, float(r.inputs[good_id]) * iters)
			if r.output != "":
				isl.add(r.output, r.output_qty * iters * _prod_mult(r.output))
			pb.progress -= iters * r.iteration_time
			pb.active = true
		else:
			pb.progress = min(pb.progress, r.iteration_time)

# Phases 3-5: per house, consume needs, move residents, pay out.
func _phase_population(isl: Island, dt: float) -> void:
	for pb in isl.buildings:
		var def := Database.building(pb.building_id)
		if def == null or not def.is_house:
			continue
		var tier := Database.tier(pb.tier_id)
		if tier == null:
			continue
		if not pb.connected:
			pb.active = false
			continue
		var basics := _consume_needs(isl, tier.basic_needs, pb.residents, dt)
		var lux := _consume_needs(isl, tier.luxury_needs, pb.residents, dt)
		pb.active = pb.residents > 0
		# Phase 4: population dynamics — basics drive occupancy with hysteresis.
		# Timers SUBTRACT whole intervals (never reset to 0) so the remainder carries
		# and the outcome is independent of how dt was chopped. while-loops handle a
		# single large (offline) step crossing several intervals.
		if basics.all_met:
			pb.unmet_time = 0.0
			pb.satisfied_time += dt
			while pb.residents < tier.max_residents and pb.satisfied_time >= GROW_INTERVAL:
				pb.satisfied_time -= GROW_INTERVAL
				pb.residents += 1
				population_changed.emit(pb.tier_id, pb.residents, total_population())
			if pb.residents >= tier.max_residents:
				pb.satisfied_time = minf(pb.satisfied_time, GROW_INTERVAL)
		else:
			pb.satisfied_time = 0.0
			pb.unmet_time += dt
			while pb.unmet_time >= EMIGRATE_INTERVAL and pb.residents > 0:
				pb.unmet_time -= EMIGRATE_INTERVAL
				pb.residents -= 1
				needs_unmet.emit(pb.tier_id, _first_missing(isl, tier))
				population_changed.emit(pb.tier_id, pb.residents, total_population())
		# Phase 5: economy payout — scales with luxury satisfaction fraction.
		if pb.residents > 0:
			if tier.coin_per_resident_per_min > 0.0:
				currencies["coin"] += tier.coin_per_resident_per_min / 60.0 \
					* pb.residents * lux.ratio * dt * _tax_mult()
			else:
				currencies["favor"] += FAVOR_PER_PARAGON_PER_MIN / 60.0 \
					* pb.residents * lux.ratio * dt
			# Recruitment: only the base population tier musters the base unit (spec:
			# Pioneers→Militia; Farmers→Slingers when the rural chain exists). Higher
			# tiers pay Coin instead, so a player keeps a Pioneer district for troops.
			if basics.all_met and pb.tier_id == "pioneers":
				isl.add("militia", pb.residents * (MILITIA_PER_POP_PER_MIN / 60.0)
					* dt * maxf(lux.ratio, 0.25))

## Consume each need good from the island stockpile at residents/denominator per sec.
## Returns {"ratio": min fraction met across goods, "all_met": every good fully met}.
func _consume_needs(isl: Island, needs: Dictionary, residents: int, dt: float) -> Dictionary:
	if residents <= 0 or needs.is_empty():
		return {"ratio": 1.0, "all_met": true}
	var min_ratio := 1.0
	var all_met := true
	for good_id in needs:
		var denom: float = needs[good_id]
		if denom <= 0.0:
			continue
		var want: float = residents * (1.0 / denom) * dt
		if want <= 0.0:
			continue
		var got := isl.take(good_id, want)
		var ratio: float = got / want
		min_ratio = min(min_ratio, ratio)
		if ratio < 0.999:
			all_met = false
	return {"ratio": min_ratio, "all_met": all_met}

func _first_missing(isl: Island, tier: PopTierDef) -> String:
	for good_id in tier.basic_needs:
		if isl.qty(good_id) <= 0.0:
			return good_id
	return ""

# ── house upgrade (the cascade ascension) ──────────────────────────────────────

## Upgrade-eligible when at max residents AND every basic + luxury need has a
## comfortable buffer, and a higher tier exists. Player-triggered (PP2-faithful).
func can_upgrade(pb: PlacedBuilding) -> bool:
	var def := Database.building(pb.building_id)
	if def == null or not def.is_house:
		return false
	var tier := Database.tier(pb.tier_id)
	if tier == null or Database.next_tier_id(pb.tier_id) == "":
		return false
	if pb.residents < tier.max_residents:
		return false
	var isl := active_island()
	return _peek_needs(isl, tier.basic_needs, pb.residents) \
		and _peek_needs(isl, tier.luxury_needs, pb.residents)

func _peek_needs(isl: Island, needs: Dictionary, residents: int) -> bool:
	for good_id in needs:
		var denom: float = needs[good_id]
		if denom <= 0.0:
			continue
		# "supplied" = at least a minute's buffer of this good is on hand.
		if isl.qty(good_id) < residents * (1.0 / denom) * 60.0:
			return false
	return true

## Upgrade a house in place to the next tier; unlocks that tier's buildings.
func upgrade_house(pb: PlacedBuilding) -> bool:
	if not can_upgrade(pb):
		return false
	var next_id := Database.next_tier_id(pb.tier_id)
	var next_tier := Database.tier(next_id)
	var next_house := ""
	for bid in Database.buildings:
		var b: BuildingDef = Database.buildings[bid]
		if b.is_house and b.house_tier == next_id:
			next_house = bid
			break
	if next_house == "":
		return false
	pb.building_id = next_house
	pb.tier_id = next_id
	pb.residents = min(pb.residents, next_tier.max_residents)
	pb.satisfied_time = 0.0
	if not unlocked_tiers.has(next_id):
		unlocked_tiers.append(next_id)
		tier_unlocked.emit(next_id)
	active_island()._reindex()
	population_changed.emit(next_id, pb.residents, total_population())
	notify.emit("A house ascended to %s!" % next_tier.display_name, "good")
	return true

# ── placement API (used by the build UI) ───────────────────────────────────────

func can_afford(def: BuildingDef) -> bool:
	var isl := active_island()
	var cost := effective_cost(def)
	for good_id in cost:
		var need: float = cost[good_id]
		var have: float = currencies[good_id] if currencies.has(good_id) else isl.qty(good_id)
		if have < need:
			return false
	return true

func try_place(def: BuildingDef, origin: Vector2i) -> Dictionary:
	var isl := active_island()
	var check := isl.can_place(def, origin)
	if not check.ok:
		return check
	if def.is_palace:
		if find_palace() != null:
			return {"ok": false, "reason": "You already have a Palace"}
		if paragon_population() < PALACE_PARAGON_REQ:
			return {"ok": false, "reason": "Need %d Paragons to found a Palace" % PALACE_PARAGON_REQ}
	if not can_afford(def):
		return {"ok": false, "reason": "Not enough materials"}
	for good_id in effective_cost(def):
		var amt: float = effective_cost(def)[good_id]
		if currencies.has(good_id):
			currencies[good_id] -= amt
		else:
			isl.take(good_id, amt)
	isl.place(def, origin)
	_recompute_connectivity(isl)
	building_placed.emit(def.id, origin)
	return {"ok": true, "reason": ""}

func demolish(cell: Vector2i) -> bool:
	var isl := active_island()
	if isl.remove_at(cell):
		_recompute_connectivity(isl)
		building_removed.emit(cell)
		return true
	return false

# ── military: garrison + expeditions (M8) ───────────────────────────────────────

## The island garrison: unit_id -> whole-unit count from the stockpile (units are
## goods, so fractional Militia accrues then floors into deployable soldiers).
func garrison(isl: Island) -> Dictionary:
	var out: Dictionary = {}
	if isl == null:
		return out
	for gid in isl.stockpile:
		var gd := Database.good(gid)
		if gd != null and gd.category == "unit":
			var n := int(floor(isl.qty(gid)))
			if n > 0:
				out[gid] = n
	return out

## Total deployable soldiers on an island (for the army-cap check).
func garrison_size(isl: Island) -> int:
	var n := 0
	for uid in garrison(isl):
		n += int(garrison(isl)[uid])
	return n

func army_cap() -> int:
	return ARMY_CAP + int(_mods.get("army_cap_bonus", 0.0)) if not _mods.is_empty() else ARMY_CAP

## Is a camp already being assaulted?
func expedition_for(island_index: int, camp_id: int) -> Dictionary:
	for e in expeditions:
		if int(e.island_index) == island_index and int(e.camp_id) == camp_id:
			return e
	return {}

## Launch an expedition: deploy `army` (unit_id -> count) from the island garrison at
## `camp`. Deducts the units immediately; the battle resolves over wall-clock time.
func send_expedition(island_index: int, camp_id: int, army: Dictionary) -> Dictionary:
	if island_index < 0 or island_index >= islands.size():
		return {"ok": false, "reason": "No such island"}
	var isl := islands[island_index]
	var camp: OrcCamp = null
	for c in isl.camps:
		if c.id == camp_id:
			camp = c
			break
	if camp == null or camp.cleared:
		return {"ok": false, "reason": "No camp to attack"}
	if not expedition_for(island_index, camp_id).is_empty():
		return {"ok": false, "reason": "Already under attack"}
	var total_units := 0
	for uid in army:
		var want := int(army[uid])
		if want <= 0:
			continue
		if int(floor(isl.qty(uid))) < want:
			return {"ok": false, "reason": "Not enough %s" % Database.good_name(uid)}
		total_units += want
	if total_units <= 0:
		return {"ok": false, "reason": "Select some units to send"}
	if total_units > army_cap():
		return {"ok": false, "reason": "Army exceeds the %d-unit cap" % army_cap()}
	# Deploy: remove the units from the garrison.
	for uid in army:
		var want := int(army[uid])
		if want > 0:
			isl.take(uid, float(want))
	_exp_seq += 1
	var duration := Battle.duration_seconds(army, camp.full_army())
	duration = maxf(duration - float(_mods.get("battle_time_cut", 0.0)), 5.0)
	if float(_mods.get("battle_instant", 0.0)) > 0.0:
		duration = 0.1  # Berserk custodian: battles finish instantly
	expeditions.append({
		"island_index": island_index,
		"camp_id": camp_id,
		"army": army.duplicate(),
		"elapsed": 0.0,
		"total": duration,
		"seed": _exp_seq * 100003 + camp_id * 7 + island_index,
	})
	notify.emit("Expedition launched against %s." % camp.display_name, "info")
	expedition_launched.emit(island_index, camp_id)
	return {"ok": true, "reason": ""}

func _advance_expeditions(dt: float) -> void:
	if expeditions.is_empty():
		return
	var done: Array = []
	for e in expeditions:
		e.elapsed = float(e.elapsed) + dt
		if float(e.elapsed) >= float(e.total):
			done.append(e)
	for e in done:
		_resolve_expedition(e)
		expeditions.erase(e)

func _resolve_expedition(e: Dictionary) -> void:
	var island_index := int(e.island_index)
	if island_index < 0 or island_index >= islands.size():
		return
	var isl := islands[island_index]
	var camp: OrcCamp = null
	for c in isl.camps:
		if c.id == int(e.camp_id):
			camp = c
			break
	if camp == null:
		return
	var rng := RandomNumberGenerator.new()
	rng.seed = int(e.seed)
	var result := Battle.resolve(e.army, camp.full_army(), rng)
	var won: bool = result.winner == "attacker"
	# Survivors march home into the garrison either way (the fallen stay fallen).
	for uid in result.attacker_survivors:
		isl.add(uid, float(result.attacker_survivors[uid]))
	if won:
		camp.cleared = true
		var msg := "Victory! %s cleared." % camp.display_name
		if camp.boss != "":
			currencies["cartography"] = float(currencies.get("cartography", 0.0)) + 1.0
			msg += " +1 Cartography (warchief defeated)."
		notify.emit(msg, "good")
		world_changed.emit()
	else:
		# On a loss the camp's wounded fully heal (Orcs never reinforce — you must win
		# outright). The player keeps only the survivors that returned.
		notify.emit("Defeat at %s. The survivors retreat." % camp.display_name, "warn")
	expedition_resolved.emit(island_index, int(e.camp_id), won)

# ── world: regions · discovery · settle/handover · trade (M6/M7) ─────────────────

## Settled islands count against the per-run island limit.
func settled_island_count() -> int:
	var n := 0
	for isl in islands:
		if isl.settled:
			n += 1
	return n

func island_limit() -> int:
	var bonus: int = int(_mods.get("island_slots", 0.0)) if not _mods.is_empty() else 0
	return ISLAND_LIMIT_BASE + bonus

## Cartography discovery: dispatch a voyage to chart a new island in `region`. Spending
## more Cartography points (`points`) yields a larger island but a longer voyage
## (+10 min/point, capped at 2.5 days). Points are deducted up front; 0 is allowed
## (a free, small basic island) so expansion is never hard-gated on Cartography.
func can_discover(region: String, points: int) -> Dictionary:
	if not unlocked_regions.has(region):
		return {"ok": false, "reason": "%s region not unlocked" % region.capitalize()}
	if points < 0:
		points = 0
	if float(currencies.get("cartography", 0.0)) < float(points):
		return {"ok": false, "reason": "Not enough Cartography"}
	if settled_island_count() + discoveries.size() >= island_limit():
		return {"ok": false, "reason": "Island limit reached (%d)" % island_limit()}
	return {"ok": true, "reason": ""}

func start_discovery(region: String, points: int) -> Dictionary:
	var chk := can_discover(region, points)
	if not chk.ok:
		return chk
	points = max(points, 0)
	currencies["cartography"] = float(currencies.get("cartography", 0.0)) - float(points)
	_disc_seq += 1
	var speed := float(_mods.get("discovery_speed", 1.0)) if not _mods.is_empty() else 1.0
	var total: float = minf((DISCOVERY_TRAVEL_BASE + points * DISCOVERY_SEC_PER_POINT) * speed,
		DISCOVERY_CAP)
	discoveries.append({
		"region": region,
		"points": points,
		"size": 12 + points,  ## spec: size ~12 → large; points raise it
		"elapsed": 0.0,
		"total": total,
		"seed": _disc_seq * 7919 + points * 31 + region.hash(),
	})
	notify.emit("Charting a new %s island…" % region.capitalize(), "info")
	world_changed.emit()
	return {"ok": true, "reason": ""}

func _advance_discoveries(dt: float) -> void:
	if discoveries.is_empty():
		return
	var done: Array = []
	for d in discoveries:
		d.elapsed = float(d.elapsed) + dt
		if float(d.elapsed) >= float(d.total):
			done.append(d)
	for d in done:
		_complete_discovery(d)
		discoveries.erase(d)

func _complete_discovery(d: Dictionary) -> void:
	var size := int(d.get("size", 12))
	var grid: int = clampi(size + 8, 20, 48)
	var region := String(d.get("region", "temperate"))
	# A discovered island always hosts its size's warchief fort plus a plain camp.
	var boss := Database.warchief_for_size(size)
	var isl := MapGen.generate(grid, grid, int(d.get("seed", 1)), region, 2, boss)
	isl.discovered = true
	isl.settled = false
	isl.island_name = _name_for(region, islands.size())
	islands.append(isl)
	notify.emit("Discovered %s! Conquer its forts to settle it." % isl.island_name, "good")
	world_changed.emit()

func _name_for(region: String, idx: int) -> String:
	var pools := {
		"temperate": ["Greenholm", "Oakmoor", "Westcliff", "Thornbay", "Elderisle"],
		"tropical": ["Palmyra", "Coral Key", "Sunjade", "Mango Cay", "Azure Atoll"],
		"northern": ["Frosthold", "Grimfjord", "Snowreach", "Icebourne", "Palebrook"],
	}
	var pool: Array = pools.get(region, ["New Isle"])
	return pool[idx % pool.size()]

## Keep & settle a discovered island (must be pacified — all forts cleared).
func settle_island(index: int) -> Dictionary:
	if index < 0 or index >= islands.size():
		return {"ok": false, "reason": "No such island"}
	var isl := islands[index]
	if isl.settled:
		return {"ok": false, "reason": "Already settled"}
	if not isl.active_camps().is_empty():
		return {"ok": false, "reason": "Clear the Orc forts first"}
	if settled_island_count() >= island_limit():
		return {"ok": false, "reason": "Island limit reached"}
	isl.settled = true
	# A freshly settled island needs a coastal Kontor and starter materials.
	isl.stockpile = {"wood": 80.0, "plank": 30.0}
	_place_starting_kontor(isl)
	_recompute_connectivity(isl)
	notify.emit("Settled %s." % isl.island_name, "good")
	world_changed.emit()
	return {"ok": true, "reason": ""}

## Hand a discovered island to the Paragons for Favor (spec formula by size).
func handover_to_paragons(index: int) -> Dictionary:
	if index < 0 or index >= islands.size():
		return {"ok": false, "reason": "No such island"}
	var isl := islands[index]
	if isl.settled:
		return {"ok": false, "reason": "Can't hand over your home"}
	if not isl.active_camps().is_empty():
		return {"ok": false, "reason": "Clear the Orc forts first"}
	var size := maxi(isl.width - 8, 12)
	var favor := Database.favor_for_size(size)
	currencies["favor"] = float(currencies.get("favor", 0.0)) + favor
	notify.emit("Handed %s to the Paragons. +%d Favor." % [isl.island_name, int(favor)], "good")
	_remove_island(index)
	return {"ok": true, "reason": ""}

## Turn a discovered island in for Coins instead.
func turn_in_for_coins(index: int) -> Dictionary:
	if index < 0 or index >= islands.size():
		return {"ok": false, "reason": "No such island"}
	var isl := islands[index]
	if isl.settled:
		return {"ok": false, "reason": "Can't turn in your home"}
	if not isl.active_camps().is_empty():
		return {"ok": false, "reason": "Clear the Orc forts first"}
	var size := maxi(isl.width - 8, 12)
	var coins := float(size) * 250.0  ## CHOSEN DEFAULT turn-in value
	currencies["coin"] = float(currencies.get("coin", 0.0)) + coins
	notify.emit("Turned in %s for %d Coin." % [isl.island_name, int(coins)], "good")
	_remove_island(index)
	return {"ok": true, "reason": ""}

func _remove_island(index: int) -> void:
	# Drop any trade routes / expeditions touching the island, then re-index the rest.
	trade_routes = trade_routes.filter(func(r):
		return int(r.from) != index and int(r.to) != index)
	expeditions = expeditions.filter(func(e): return int(e.island_index) != index)
	islands.remove_at(index)
	if active_index >= islands.size():
		active_index = max(0, islands.size() - 1)
	# Shift route/expedition indices above the removed one.
	for r in trade_routes:
		if int(r.from) > index: r.from = int(r.from) - 1
		if int(r.to) > index: r.to = int(r.to) - 1
	for e in expeditions:
		if int(e.island_index) > index: e.island_index = int(e.island_index) - 1
	world_changed.emit()

# ── trade routes (ships moving goods between islands) ────────────────────────────

## Create a route shipping `good` from island `from_idx` to `to_idx` using ship class
## `ship_id`. Requires a Shipyard on either endpoint; cross-region needs a crossing hull.
func add_trade_route(from_idx: int, to_idx: int, good: String, ship_id: String) -> Dictionary:
	if from_idx == to_idx or from_idx < 0 or to_idx < 0 \
			or from_idx >= islands.size() or to_idx >= islands.size():
		return {"ok": false, "reason": "Pick two different islands"}
	var ship := Database.ship(ship_id)
	if ship == null:
		return {"ok": false, "reason": "Unknown ship"}
	if not (_has_shipyard(islands[from_idx]) or _has_shipyard(islands[to_idx])):
		return {"ok": false, "reason": "Need a Shipyard on one island"}
	if islands[from_idx].region != islands[to_idx].region and not ship.cross_region:
		return {"ok": false, "reason": "%s can't cross regions" % ship.display_name}
	if float(currencies.get("coin", 0.0)) < float(ship.coin_cost):
		return {"ok": false, "reason": "Need %d Coin for a %s" % [ship.coin_cost, ship.display_name]}
	currencies["coin"] = float(currencies.get("coin", 0.0)) - float(ship.coin_cost)
	trade_routes.append({"from": from_idx, "to": to_idx, "good": good,
		"ship": ship_id, "rate": ship.goods_per_hour})
	notify.emit("Trade route: %s → %s (%s)" % [islands[from_idx].island_name,
		islands[to_idx].island_name, Database.good_name(good)], "good")
	return {"ok": true, "reason": ""}

func remove_trade_route(idx: int) -> void:
	if idx >= 0 and idx < trade_routes.size():
		trade_routes.remove_at(idx)

func _has_shipyard(isl: Island) -> bool:
	for pb in isl.buildings:
		var def := Database.building(pb.building_id)
		if def != null and def.is_shipyard:
			return true
	return false

func _advance_trade(dt: float) -> void:
	for r in trade_routes:
		var fi := int(r.from)
		var ti := int(r.to)
		if fi >= islands.size() or ti >= islands.size():
			continue
		var src := islands[fi]
		var dst := islands[ti]
		var tmult := float(_mods.get("trade_mult", 1.0)) if not _mods.is_empty() else 1.0
		var want: float = float(r.rate) * tmult / 3600.0 * dt  ## goods/hour → per-second
		var moved := src.take(String(r.good), want)
		dst.add(String(r.good), moved)

# ── prestige: Custodian starts · the Palace · Reputation (M10) ───────────────────

## Apply one-time starting grants from the active Custodians (called at new_game).
func _apply_custodian_starts() -> void:
	for cid in active_custodians:
		var c := Database.custodian(cid)
		if c == null:
			continue
		match String(c.effect.get("type", "")):
			"start_cartography":
				currencies["cartography"] = float(currencies.get("cartography", 0.0)) + float(c.effect.value)
			"start_creativity":
				creativity += float(c.effect.value)
			"start_coin":
				currencies["coin"] = float(currencies.get("coin", 0.0)) + float(c.effect.value)

func paragon_population() -> int:
	var n := 0
	for isl in islands:
		for pb in isl.buildings:
			if pb.tier_id == "paragons":
				n += pb.residents
	return n

## The Palace placed in the world (there is at most one).
func find_palace() -> PlacedBuilding:
	for isl in islands:
		for pb in isl.buildings:
			var def := Database.building(pb.building_id)
			if def != null and def.is_palace:
				return pb
	return null

## Favor cost to raise the Palace from its current stage to the next ( -1 if maxed).
func palace_stage_cost(level: int) -> float:
	if level < 0 or level >= PALACE_STAGE_FAVOR.size():
		return -1.0
	return PALACE_STAGE_FAVOR[level]

func can_upgrade_palace(pb: PlacedBuilding) -> bool:
	var def := Database.building(pb.building_id)
	if def == null or not def.is_palace or pb.level >= PALACE_MAX_STAGE:
		return false
	return float(currencies.get("favor", 0.0)) >= palace_stage_cost(pb.level)

## Upgrade the Palace one stage, spending Favor. Completing the final stage grants a
## permanent Reputation point (the roguelite soft-win).
func upgrade_palace(pb: PlacedBuilding) -> bool:
	if not can_upgrade_palace(pb):
		return false
	var cost := palace_stage_cost(pb.level)
	currencies["favor"] = float(currencies.get("favor", 0.0)) - cost
	pb.level += 1
	if pb.level >= PALACE_MAX_STAGE:
		currencies["reputation"] = float(currencies.get("reputation", 0.0)) + 1.0
		notify.emit("The Palace is complete! +1 Reputation. Pick a Custodian for a new world.", "good")
		reputation_earned.emit(int(currencies.reputation))
	else:
		notify.emit("Palace raised to stage %d / %d." % [pb.level, PALACE_MAX_STAGE], "good")
	return true

func reputation() -> int:
	return int(currencies.get("reputation", 0.0))

## Custodians the player can pick given their permanent Reputation total.
func available_custodians() -> Array:
	var out: Array = []
	for cid in Database.all_custodians():
		var c := Database.custodian(cid)
		if c != null and reputation() >= c.rep_cost:
			out.append(cid)
	return out

# ── aggregates for UI ──────────────────────────────────────────────────────────

func total_population() -> int:
	var n := 0
	for isl in islands:
		for pb in isl.buildings:
			n += pb.residents
	return n

func population_by_tier() -> Dictionary:
	var out: Dictionary = {}
	for isl in islands:
		for pb in isl.buildings:
			if pb.residents > 0 and pb.tier_id != "":
				out[pb.tier_id] = int(out.get(pb.tier_id, 0)) + pb.residents
	return out

func coin() -> float:
	return currencies.get("coin", 0.0)

# ── research (Creativity) ───────────────────────────────────────────────────────

## Rebuild the derived economy modifiers from the researched perk list. Safe to call
## any time; an empty `researched` yields all-neutral modifiers.
func _recompute_mods() -> void:
	_mods = {"tax_mult": 1.0, "creativity_mult": 1.0, "prod_mult_all": 1.0,
		"prod_mult": {}, "build_cost_flat": {}, "army_cap_bonus": 0.0,
		"battle_time_cut": 0.0, "island_slots": 0.0, "discovery_speed": 1.0,
		"trade_mult": 1.0, "battle_instant": 0.0}
	# Custodian effects are persistent run-modifiers (same effect grammar as perks).
	for cid in active_custodians:
		var c := Database.custodian(cid)
		if c != null:
			_apply_effect(c.effect)
	for pid in researched:
		var p := Database.research_perk(pid)
		if p == null:
			continue
		_apply_effect(p.effect)

## Fold one {type,value[,key]} effect into the derived modifier table.
func _apply_effect(e: Dictionary) -> void:
		match String(e.get("type", "")):
			"trade_mult":
				_mods.trade_mult += float(e.value)
			"battle_instant":
				_mods.battle_instant = 1.0
			"start_cartography", "start_creativity", "start_coin":
				pass  # one-time grants, applied in _apply_custodian_starts()
			"tax_mult":
				_mods.tax_mult += float(e.value)
			"creativity_mult":
				_mods.creativity_mult += float(e.value)
			"prod_mult_all":
				_mods.prod_mult_all += float(e.value)
			"prod_mult":
				var k := String(e.key)
				_mods.prod_mult[k] = float(_mods.prod_mult.get(k, 1.0)) + float(e.value)
			"build_cost_flat":
				var k := String(e.key)
				_mods.build_cost_flat[k] = float(_mods.build_cost_flat.get(k, 0.0)) + float(e.value)
			"army_cap_bonus":
				_mods.army_cap_bonus += float(e.value)
			"battle_time_cut":
				_mods.battle_time_cut += float(e.value)
			"island_slots":
				_mods.island_slots += float(e.value)
			"discovery_speed":
				_mods.discovery_speed += float(e.value)
			"unlock_region":
				var region := String(e.value)
				if not unlocked_regions.has(region):
					unlocked_regions.append(region)

func _prod_mult(good_id: String) -> float:
	if _mods.is_empty():
		return 1.0
	return float(_mods.prod_mult_all) * float(_mods.prod_mult.get(good_id, 1.0))

func _tax_mult() -> float:
	return float(_mods.get("tax_mult", 1.0)) if not _mods.is_empty() else 1.0

func research_rank(perk_id: String) -> int:
	return researched.count(perk_id)

## Creativity cost of the next rank (repeatable perks scale by rank).
func research_cost(perk: ResearchDef) -> int:
	return perk.cost * (research_rank(perk.id) + 1) if perk.repeatable else perk.cost

## Available = its tree is unlocked (tier reached, or "infinite") and, for one-shot
## perks, it isn't already researched.
func research_available(perk: ResearchDef) -> bool:
	if perk.tree != "infinite" and not unlocked_tiers.has(perk.tree):
		return false
	if not perk.repeatable and researched.has(perk.id):
		return false
	return true

func can_research(perk: ResearchDef) -> bool:
	return research_available(perk) and creativity >= float(research_cost(perk))

func research(perk: ResearchDef) -> bool:
	if not can_research(perk):
		return false
	creativity -= float(research_cost(perk))
	researched.append(perk.id)
	_recompute_mods()
	research_completed.emit(perk.id)
	notify.emit("Researched: %s" % perk.display_name, "good")
	return true

## Build cost after research reductions (build_cost_flat), clamped at 0.
func effective_cost(def: BuildingDef) -> Dictionary:
	var out: Dictionary = {}
	var flat: Dictionary = _mods.get("build_cost_flat", {}) if not _mods.is_empty() else {}
	for g in def.cost:
		out[g] = maxf(0.0, float(def.cost[g]) - float(flat.get(g, 0.0)))
	return out

# ── persistence (offline catch-up happens here) ─────────────────────────────────

func to_dict() -> Dictionary:
	var isl_list: Array = []
	for isl in islands:
		isl_list.append(isl.to_dict())
	return {
		"islands": isl_list,
		"active_index": active_index,
		"currencies": currencies.duplicate(),
		"unlocked_tiers": unlocked_tiers.duplicate(),
		"unlocked_regions": unlocked_regions.duplicate(),
		"creativity": creativity,
		"researched": researched.duplicate(),
		"elapsed": elapsed,
		"expeditions": expeditions.duplicate(true),
		"discoveries": discoveries.duplicate(true),
		"trade_routes": trade_routes.duplicate(true),
		"active_custodians": active_custodians.duplicate(),
		"exp_seq": _exp_seq,
		"disc_seq": _disc_seq,
		"saved_at_unix": Time.get_unix_time_from_system(),
	}

func from_dict(d: Dictionary) -> void:
	_tick_accum = 0.0
	islands.clear()
	for isl_d in d.get("islands", []):
		islands.append(Island.from_dict(isl_d))
	active_index = int(d.get("active_index", 0))
	currencies = {"coin": 0.0, "cartography": 0.0, "favor": 0.0, "reputation": 0.0}
	var cur: Dictionary = d.get("currencies", {})
	for k in cur:
		currencies[k] = float(cur[k])
	unlocked_tiers = d.get("unlocked_tiers", ["pioneers"])
	creativity = float(d.get("creativity", 0.0))
	researched = d.get("researched", [])
	unlocked_regions = d.get("unlocked_regions", ["temperate"])
	expeditions = d.get("expeditions", [])
	discoveries = d.get("discoveries", [])
	trade_routes = d.get("trade_routes", [])
	active_custodians = d.get("active_custodians", [])
	_exp_seq = int(d.get("exp_seq", 0))
	_disc_seq = int(d.get("disc_seq", 0))
	_recompute_mods()
	elapsed = float(d.get("elapsed", 0.0))
	for isl in islands:
		_recompute_connectivity(isl)
	# Idle/offline catch-up: simulate bounded wall-clock elapsed since the save.
	var saved_at: float = float(d.get("saved_at_unix", 0.0))
	if saved_at > 0.0:
		var away: float = clampf(Time.get_unix_time_from_system() - saved_at,
			0.0, Constants.MAX_OFFLINE_SECONDS)
		if away > 1.0:
			catch_up(away)
			notify.emit("Welcome back — simulated %d min away." % int(away / 60.0), "info")
